export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING'
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS'
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED'

export const REQUEST_QUESTIONS_PENDING = 'REQUEST_QUESTIONS_PENDING'
export const REQUEST_QUESTIONS_SUCCESS = 'REQUEST_QUESTIONS_SUCCESS'
export const REQUEST_QUESTIONS_FAILED = 'REQUEST_QUESTIONS_FAILED'

export const SET_AUTH_USER = 'SET_AUTH_USER'